# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pose_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pose_message.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\",\n\tPoseFrame\x12\x1f\n\rjoint_vectors\x18\x01 \x03(\x0b\x32\x08.Vector3\"(\n\nPoseSample\x12\x1a\n\x06\x66rames\x18\x01 \x03(\x0b\x32\n.PoseFrameB\x1d\xaa\x02\x1aTFLitePoseTrainer.Messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\032TFLitePoseTrainer.Messages'
  _globals['_VECTOR3']._serialized_start=22
  _globals['_VECTOR3']._serialized_end=64
  _globals['_POSEFRAME']._serialized_start=66
  _globals['_POSEFRAME']._serialized_end=110
  _globals['_POSESAMPLE']._serialized_start=112
  _globals['_POSESAMPLE']._serialized_end=152
# @@protoc_insertion_point(module_scope)
